# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_WT_PROJECT_S96818AA1) += mt6768.dtb
dtb-$(CONFIG_WT_PROJECT_S96818AA1) += mt6769v_a05m_eur_open_00.dtb

dtb-$(CONFIG_WT_PROJECT_S96616AA1) += mt6765.dtb
dtb-$(CONFIG_WT_PROJECT_S96616AA1) += mt6765_a04_eur_open_00.dtb

always            := $(dtb-y)
clean-files       := *.dtb*
